Organization info lookup by INN
VantaFinance/DaDataClient pull request #15
Opened 2024-03-25 14:15 UTC by kozlice

2024-03-25 14:18 UTC, kozlice commented on src/Infrastructure/Serializer/PhoneNumberNormalizer.php
> +final class PhoneNumberNormalizer implements Normalizer, Denormalizer
Альтернативно можно сделать OrganizationPhone и у него `private PhoneNumber $value`

2024-03-25 14:58 UTC, root-aza requested changes

2024-03-25 14:58 UTC, root-aza commented on src/Response/OrganizationBranchType.php
> +    private const BRANCH = 'BRANCH';
UNKNOWN добавь статус, кастуй к нему если попался неизвестный

2024-03-25 14:58 UTC, root-aza commented on src/Response/OrganizationStateStatus.php
> +    public static function active(): self
Тоже самое UNKNOWN

2024-03-25 16:58 UTC, root-aza commented on src/Transport/RestSuggestOrganizationClient.php
> +    public function findByInn(string $inn): array
поддержки count нету?

2024-03-25 17:29 UTC, kozlice commented on src/Transport/RestSuggestOrganizationClient.php
> +    public function findByInn(string $inn): array
Нашёл, есть, добавил

2024-03-25 17:30 UTC, kozlice commented on src/Response/Organization.php
> +    private ?string $okpo;
Сделал опциональными все коды, кроме ИНН, ОГРН и ОКВЭД. Потому что у ИП не будет КПП, а у "Газпрома" того же нет ОКПО в dadata

2024-03-26 04:07 UTC, root-aza requested changes

2024-03-26 04:07 UTC, root-aza commented on src/Infrastructure/Serializer/OrganizationBranchTypeNormalizer.php
> +        return OrganizationBranchType::isValid($data)
а так сделай в EnumNormalizer и делай там fallback. в mdm-client есть пример

2024-03-26 11:08 UTC, root-aza commented on src/Response/Organization.php
> +        $this->phones      = array_filter($phones ?? []);
фильтр явно прокинь))

2024-03-26 12:32 UTC, merged